### ISSUE TITLE
I can't program.

### ISSUE THREAD

**Issue by T9235** [project-sbc/Handheld-Hardware-Tools#15]
I want to install this program and it says You must install .NET Desktop Runtime to run this application.

Architecture: x64 App host version: 6.0.28

orts

Would you like to download it now?

Learn about runtime installation: https://aka.ms/dotnet/app-launch-failed How do I get old?

**Comment by project-sbc** [comment]
I’m not sure what the issue is, you just need to install .net runtime from the prompt and it should work afterward

Let me know!

**Comment by T9235** [comment]
Now I can program but it doesn't work, is there a way to program, I'm not as good at computers as my shoulders.

**Comment by project-sbc** [comment]
solved this issue on discord, needed correct .net version and it was fixed
